### ISSUE TITLE
Workflow does not work with "nextjs-pages" 14.2.15 and QStash 2.7.12

### ISSUE THREAD

**Issue by mkv27** [upstash/qstash-js#199]
Using latest next 14 and QStash versions, here is the error message:

```sh
 ⨯ Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/project/workspace/node_modules/next/server' imported from /project/workspace/node_modules/@upstash/qstash/nextjs.mjs
Did you mean to import next/server.js?
```

Repro here:
https://codesandbox.io/p/devbox/79yx3q
The app router version seems to work, but the pages version throws that error

Note it's using:
```sh
 "module": "esnext",
 "moduleResolution": "bundler",
 ```

**Comment by vacom** [comment]
I'm also having the same problem as you with the same versions using Pages Router. I can't use the new Workflow because it gives me the error you're having

**Comment by mkv27** [comment]
@vacom It’s not ideal, but in the meantime, if you can, just use the app router for the workflows. I tested it, and everything works perfectly there

**Comment by vacom** [comment]
@mkv27 Yes, I can confirm that it works on App Router, but I'd like to keep it consistent. I can use App Router for this until the fix for Pages Router arrives. Thanks for the tip

**Comment by CahidArda** [comment]
Hi @mkv27 @vacom,

We believe we addressed this issue in release v2.7.13. Can you check again?

**Comment by mkv27** [comment]
@CahidArda I can confirm 2.7.13 fix that, that version works in pages and app router. Thank you!!
